#include <Arduino.h>
#include "esp_camera.h"
#include "img_converters.h"
#include "esp_heap_caps.h"
#include <IRremoteESP8266.h>
#include <IRsend.h>
#include "camera_pins.h"

// Edge Impulse SDK includes (uncomment after downloading library)
#include <edge-impulse-sdk/classifier/ei_run_classifier.h>
#include <edge-impulse-sdk/dsp/image/image.hpp>

// --- Embedded Test Images ---
// These symbols are automatically generated by PlatformIO's embed_files feature
extern const uint8_t prog1_start[] asm("_binary_Test_Images_program_01_jpg_start");
extern const uint8_t prog1_end[]   asm("_binary_Test_Images_program_01_jpg_end");
extern const uint8_t prog2_start[] asm("_binary_Test_Images_program_02_jpg_start");
extern const uint8_t prog2_end[]   asm("_binary_Test_Images_program_02_jpg_end");
extern const uint8_t prog3_start[] asm("_binary_Test_Images_program_03_jpg_start");
extern const uint8_t prog3_end[]   asm("_binary_Test_Images_program_03_jpg_end");
extern const uint8_t prog4_start[] asm("_binary_Test_Images_program_04_jpg_start");
extern const uint8_t prog4_end[]   asm("_binary_Test_Images_program_04_jpg_end");
extern const uint8_t prog5_start[] asm("_binary_Test_Images_program_05_jpg_start");
extern const uint8_t prog5_end[]   asm("_binary_Test_Images_program_05_jpg_end");

extern const uint8_t comm1_start[] asm("_binary_Test_Images_commercial_01_jpg_start");
extern const uint8_t comm1_end[]   asm("_binary_Test_Images_commercial_01_jpg_end");
extern const uint8_t comm2_start[] asm("_binary_Test_Images_commercial_02_jpg_start");
extern const uint8_t comm2_end[]   asm("_binary_Test_Images_commercial_02_jpg_end");
extern const uint8_t comm3_start[] asm("_binary_Test_Images_commercial_03_jpg_start");
extern const uint8_t comm3_end[]   asm("_binary_Test_Images_commercial_03_jpg_end");
extern const uint8_t comm4_start[] asm("_binary_Test_Images_commercial_04_jpg_start");
extern const uint8_t comm4_end[]   asm("_binary_Test_Images_commercial_04_jpg_end");
extern const uint8_t comm5_start[] asm("_binary_Test_Images_commercial_05_jpg_start");
extern const uint8_t comm5_end[]   asm("_binary_Test_Images_commercial_05_jpg_end");

const uint8_t* test_imgs[] = {
    prog1_start, prog2_start, prog3_start, prog4_start, prog5_start,
    comm1_start, comm2_start, comm3_start, comm4_start, comm5_start
};
const size_t test_sizes[] = {
    (size_t)(prog1_end - prog1_start), (size_t)(prog2_end - prog2_start),
    (size_t)(prog3_end - prog3_start), (size_t)(prog4_end - prog4_start),
    (size_t)(prog5_end - prog5_start),
    (size_t)(comm1_end - comm1_start), (size_t)(comm2_end - comm2_start),
    (size_t)(comm3_end - comm3_start), (size_t)(comm4_end - comm4_start),
    (size_t)(comm5_end - comm5_start)
};
// ----------------------------

// -----------------------------------------------------
// DISCRETE MUTE ON (Pronto Hex format)
// -----------------------------------------------------
uint16_t muteOnPronto[] = {
  0x0000, 0x0071, 0x0000, 0x0022, 0x0020, 0x0020, 0x0020, 0x0020, 
  0x0020, 0x0020, 0x0040, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 
  0x0020, 0x00A1, 0x0020, 0x0020, 0x0020, 0x0040, 0x0020, 0x0020, 
  0x0040, 0x0040, 0x0040, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 
  0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0AAB, 0x0020, 0x0020, 
  0x0020, 0x0020, 0x0020, 0x0020, 0x0040, 0x0020, 0x0020, 0x0020, 
  0x0020, 0x0020, 0x0020, 0x00A1, 0x0020, 0x0020, 0x0020, 0x0040, 
  0x0020, 0x0020, 0x0040, 0x0040, 0x0040, 0x0020, 0x0020, 0x0020,
  0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0AAB
};

// -----------------------------------------------------
// DISCRETE MUTE OFF / UNMUTE (Pronto Hex format)
// -----------------------------------------------------
uint16_t muteOffPronto[] = {
  0x0000, 0x0071, 0x0000, 0x0020, 0x0020, 0x0020, 0x0040, 0x0040, 
  0x0040, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x00A1, 
  0x0020, 0x0020, 0x0020, 0x0040, 0x0020, 0x0020, 0x0040, 0x0040, 
  0x0040, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 
  0x0020, 0x0040, 0x0020, 0x0AAB, 0x0020, 0x0020, 0x0040, 0x0040, 
  0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x00A1, 0x0020, 
  0x0020, 0x0020, 0x0040, 0x0020, 0x0020, 0x0040, 0x0040, 0x0040, 
  0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020,
  0x0020, 0x0040, 0x0020, 0x0AAB
};


// IR_SEND_PIN comes from camera_pins.h (board-specific)
#define COMMERCIAL_CONFIRM_FRAMES 10
#define PROGRAM_CONFIRM_FRAMES 2
#define MUTE_TOGGLE_CODE 0xE0E040BFu

IRsend irsend(IR_SEND_PIN);
static bool commercialMode = false;
static uint8_t commercialCount = 0;
static uint8_t programCount = 0;

static camera_config_t camera_config = {
    .pin_pwdn = PWDN_GPIO_NUM,
    .pin_reset = RESET_GPIO_NUM,
    .pin_xclk = XCLK_GPIO_NUM,
    .pin_sccb_sda = SIOD_GPIO_NUM,
    .pin_sccb_scl = SIOC_GPIO_NUM,
    .pin_d7 = Y9_GPIO_NUM,
    .pin_d6 = Y8_GPIO_NUM,
    .pin_d5 = Y7_GPIO_NUM,
    .pin_d4 = Y6_GPIO_NUM,
    .pin_d3 = Y5_GPIO_NUM,
    .pin_d2 = Y4_GPIO_NUM,
    .pin_d1 = Y3_GPIO_NUM,
    .pin_d0 = Y2_GPIO_NUM,
    .pin_vsync = VSYNC_GPIO_NUM,
    .pin_href = HREF_GPIO_NUM,
    .pin_pclk = PCLK_GPIO_NUM,
    .xclk_freq_hz = XCLK_FREQ_HZ,
    .ledc_timer = LEDC_TIMER_0,
    .ledc_channel = LEDC_CHANNEL_0,
    .pixel_format = PIXFORMAT_JPEG,   // Revert to stable JPEG
    .frame_size = FRAMESIZE_QVGA,
    .jpeg_quality = 12,               // MUST match data_collection.cpp exactly!
    .fb_count = 1       // Reverted to 1 to prevent stale frames in the queue
};

static bool initCamera() {
    // Aggressive hardware reset to un-freeze the camera sensor (only if PWDN
    // is actually wired — Freenove S3 has PWDN_GPIO_NUM=-1).
    if (camera_config.pin_pwdn >= 0) {
        pinMode(camera_config.pin_pwdn, OUTPUT);
        digitalWrite(camera_config.pin_pwdn, HIGH); // Power Down
        delay(500); // Wait half a second for capacitors to drain
        digitalWrite(camera_config.pin_pwdn, LOW);  // Power Up
        delay(500); // Wait half a second for sensor to boot
    }

    esp_err_t err = esp_camera_init(&camera_config);
    if (err != ESP_OK) {
        Serial.printf("Camera init failed with error 0x%x. Retrying in 2 seconds...\n", err);
        delay(2000);

        // Try one more aggressive reset (only if PWDN is wired)
        if (camera_config.pin_pwdn >= 0) {
            digitalWrite(camera_config.pin_pwdn, HIGH);
            delay(1000);
            digitalWrite(camera_config.pin_pwdn, LOW);
            delay(1000);
        }
        
        err = esp_camera_init(&camera_config);
        if (err != ESP_OK) {
            Serial.printf("Camera init failed again with error 0x%x\n", err);
            return false;
        }
    }
    return true;
}

// Helper function to encode image to base64 so you can view it in your browser
String base64Encode(const uint8_t *data, size_t len) {
    static const char base64_chars[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    String encoded;
    encoded.reserve(((len + 2) / 3) * 4);
    int val = 0, valb = -6;
    for (size_t i = 0; i < len; i++) {
        val = (val << 8) + data[i];
        valb += 8;
        while (valb >= 0) {
            encoded += base64_chars[(val >> valb) & 0x3F];
            valb -= 6;
        }
    }
    if (valb > -6) encoded += base64_chars[((val << 8) >> (valb + 8)) & 0x3F];
    while (encoded.length() % 4) encoded += '=';
    return encoded;
}

// Simple center-crop + nearest-neighbor resize. Replaces EI's
// crop_and_interpolate_rgb888 which has a destination buffer overrun bug that
// corrupts the PSRAM heap on this build. Mimics EI's "fit shortest axis":
// center-crop the longer side to a square, then downsample.
static void simple_resize_rgb888(const uint8_t *src, int src_w, int src_h,
                                 uint8_t *dst, int dst_w, int dst_h) {
    int crop_size = src_w < src_h ? src_w : src_h;
    int crop_x = (src_w - crop_size) / 2;
    int crop_y = (src_h - crop_size) / 2;
    for (int y = 0; y < dst_h; y++) {
        int sy = crop_y + (y * crop_size) / dst_h;
        const uint8_t *src_row = src + (sy * src_w + crop_x) * 3;
        uint8_t *dst_row = dst + y * dst_w * 3;
        for (int x = 0; x < dst_w; x++) {
            int sx = (x * crop_size) / dst_w;
            dst_row[x * 3 + 0] = src_row[sx * 3 + 0];
            dst_row[x * 3 + 1] = src_row[sx * 3 + 1];
            dst_row[x * 3 + 2] = src_row[sx * 3 + 2];
        }
    }
}

// Utility to safely extract true JPEG dimensions from the header
bool get_jpeg_dims(const uint8_t *data, size_t len, uint16_t *width, uint16_t *height) {
    if (len < 4 || data[0] != 0xFF || data[1] != 0xD8) return false;
    size_t i = 2;
    while (i < len - 8) {
        if (data[i] == 0xFF) {
            uint8_t marker = data[i+1];
            if (marker == 0xFF) { i++; continue; } // padding
            if (marker == 0xC0 || marker == 0xC1 || marker == 0xC2) { // SOF markers
                *height = (data[i+5] << 8) | data[i+6];
                *width = (data[i+7] << 8) | data[i+8];
                return true;
            }
            size_t marker_len = (data[i+2] << 8) | data[i+3];
            if (i + 2 + marker_len >= len) return false;
            i += 2 + marker_len;
        } else {
            i++;
        }
    }
    return false;
}

bool classifyCommercial(camera_fb_t *fb) {
    Serial.printf("[stage] enter classifyCommercial fb=%p buf=%p len=%u w=%u h=%u fmt=%d\n",
                  fb, fb ? fb->buf : nullptr,
                  fb ? (unsigned)fb->len : 0u,
                  fb ? fb->width : 0u, fb ? fb->height : 0u,
                  fb ? (int)fb->format : -1);
    Serial.flush();
    // Validate true dimensions to prevent heap corruption during decoding!
    if (fb->format == PIXFORMAT_JPEG) {
        uint16_t real_w = 0, real_h = 0;
        if (get_jpeg_dims(fb->buf, fb->len, &real_w, &real_h)) {
            if (fb->width != real_w || fb->height != real_h) {
                Serial.printf("Correcting frame dimensions from %dx%d to %dx%d based on JPEG header\n", fb->width, fb->height, real_w, real_h);
                fb->width = real_w;
                fb->height = real_h;
            }
        }
    }

    // --- Hardware Glitch & OOM Protection ---
    // We allow up to VGA (640x480) if PSRAM is present, but limit memory to prevent crashes.
    if (fb->width > 640 || fb->height > 480) {
        Serial.printf("WARNING: Image too large (%ux%u). Discarding to prevent OOM!\n", fb->width, fb->height);
        return false;
    }

    // Revert to stable buffer allocation with small safety padding
    size_t rgb_size = fb->width * fb->height * 3;
    uint8_t *rgb888_buf = (uint8_t *)heap_caps_malloc(rgb_size + 1024, MALLOC_CAP_SPIRAM);
    if (!rgb888_buf) {
        // Fallback to internal RAM if PSRAM is unavailable
        rgb888_buf = (uint8_t *)malloc(rgb_size + 1024);
    }
    if (!rgb888_buf) {
        Serial.println("Memory allocation for RGB decoding failed! PSRAM missing?");
        return false;
    }

    Serial.printf("[stage] alloc OK rgb888_buf=%p rgb_size=%u  calling fmt2rgb888\n",
                  rgb888_buf, (unsigned)rgb_size);
    Serial.flush();
    // Decode JPEG
    if (!fmt2rgb888(fb->buf, fb->len, PIXFORMAT_JPEG, rgb888_buf)) {
        Serial.println("JPEG format conversion failed!");
        free(rgb888_buf);
        return false;
    }
    Serial.println("[stage] fmt2rgb888 done");
    Serial.flush();

    // --- Diagnostics: Check if image is blank/solid color ---
    uint32_t r_sum = 0, g_sum = 0, b_sum = 0;
    size_t total_pixels = fb->width * fb->height;

    for (size_t i = 0; i < total_pixels; i++) {
        b_sum += rgb888_buf[i * 3 + 0];
        g_sum += rgb888_buf[i * 3 + 1];
        r_sum += rgb888_buf[i * 3 + 2];
    }
    uint8_t avg_r = r_sum / total_pixels;
    uint8_t avg_g = g_sum / total_pixels;
    uint8_t avg_b = b_sum / total_pixels;
    Serial.printf("Frame Avg RGB: [%u, %u, %u]\n", avg_r, avg_g, avg_b);
    Serial.flush();
    if (avg_r < 10 && avg_g < 10 && avg_b < 10) {
        Serial.println("WARNING: Camera image is completely dark!");
    } else if (avg_g > 200 && avg_r < 50 && avg_b < 50) {
        Serial.println("WARNING: Camera image is solid green (hardware glitch)!");
    }
    // --------------------------------------------------------

    uint8_t *final_rgb888_buf = rgb888_buf;
    uint8_t *scaled_rgb888_buf = NULL;

    // Only scale if the dimensions don't already perfectly match the model input!
    if (fb->width != EI_CLASSIFIER_INPUT_WIDTH || fb->height != EI_CLASSIFIER_INPUT_HEIGHT) {
        Serial.printf("[stage] Resizing %ux%u -> %ux%u\n", fb->width, fb->height,
                      EI_CLASSIFIER_INPUT_WIDTH, EI_CLASSIFIER_INPUT_HEIGHT);
        Serial.flush();
        size_t scaled_size = EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT * 3;
        scaled_rgb888_buf = (uint8_t *)heap_caps_malloc(scaled_size, MALLOC_CAP_SPIRAM);
        if (!scaled_rgb888_buf) {
            scaled_rgb888_buf = (uint8_t *)malloc(scaled_size);
        }
        if (!scaled_rgb888_buf) {
            Serial.println("Failed to allocate scaled image buffer!");
            free(rgb888_buf);
            return false;
        }

        simple_resize_rgb888(rgb888_buf, fb->width, fb->height,
                             scaled_rgb888_buf, EI_CLASSIFIER_INPUT_WIDTH, EI_CLASSIFIER_INPUT_HEIGHT);
        Serial.println("[stage] Resize complete");
        Serial.flush();

        final_rgb888_buf = scaled_rgb888_buf;
    }

    // --- VISUAL DEBUGGER: Print the exact image the AI sees! ---
    // If the image is 96x96, we construct a standard BMP to view it in the browser,
    // because fmt2jpg doesn't reliably support RGB888 formats.
    uint16_t out_w = scaled_rgb888_buf ? EI_CLASSIFIER_INPUT_WIDTH : fb->width;
    uint16_t out_h = scaled_rgb888_buf ? EI_CLASSIFIER_INPUT_HEIGHT : fb->height;
    
    /* [COMMENTED OUT PER USER REQUEST TO REDUCE CLUTTER]
    if (out_w <= 96 && out_h <= 96) {
        size_t row_padded = (out_w * 3 + 3) & (~3);
        size_t bmp_size = 54 + (row_padded * out_h);
        uint8_t *bmp_buf = (uint8_t *)malloc(bmp_size);
        if (bmp_buf) {
            memset(bmp_buf, 0, 54);
            bmp_buf[0] = 'B'; bmp_buf[1] = 'M';
            bmp_buf[2] = bmp_size & 0xFF; bmp_buf[3] = (bmp_size >> 8) & 0xFF; 
            bmp_buf[4] = (bmp_size >> 16) & 0xFF; bmp_buf[5] = (bmp_size >> 24) & 0xFF;
            bmp_buf[10] = 54; bmp_buf[14] = 40; 
            bmp_buf[18] = out_w & 0xFF; bmp_buf[19] = (out_w >> 8) & 0xFF;
            int32_t h = -out_h; // Top-down BMP
            bmp_buf[22] = h & 0xFF; bmp_buf[23] = (h >> 8) & 0xFF;
            bmp_buf[24] = (h >> 16) & 0xFF; bmp_buf[25] = (h >> 24) & 0xFF;
            bmp_buf[26] = 1; bmp_buf[28] = 24; 
            uint32_t img_size = row_padded * out_h;
            bmp_buf[34] = img_size & 0xFF; bmp_buf[35] = (img_size >> 8) & 0xFF;
            bmp_buf[36] = (img_size >> 16) & 0xFF; bmp_buf[37] = (img_size >> 24) & 0xFF;

            for (int y = 0; y < out_h; y++) {
                for (int x = 0; x < out_w; x++) {
                    size_t bmp_idx = 54 + (y * row_padded) + (x * 3);
                    size_t rgb_idx = (y * out_w + x) * 3;
                    // ESP32 fmt2rgb888 outputs BGR format.
                    // BMP format requires B, G, R order.
                    bmp_buf[bmp_idx + 0] = final_rgb888_buf[rgb_idx + 0]; // B
                    bmp_buf[bmp_idx + 1] = final_rgb888_buf[rgb_idx + 1]; // G
                    bmp_buf[bmp_idx + 2] = final_rgb888_buf[rgb_idx + 2]; // R
                }
            }
            Serial.println("\n--- COPY THE TEXT BELOW AND PASTE INTO YOUR WEB BROWSER URL BAR ---");
            Serial.print("data:image/bmp;base64,");
            Serial.println(base64Encode(bmp_buf, bmp_size));
            Serial.println("-----------------------------------------------------------------\n");
            free(bmp_buf);
        }
    } else {
        // For larger camera frames, it's faster and safer to just output the raw input JPEG.
        Serial.println("\n--- COPY THE TEXT BELOW AND PASTE INTO YOUR WEB BROWSER URL BAR ---");
        Serial.print("data:image/jpeg;base64,");
        Serial.println(base64Encode(fb->buf, fb->len));
        Serial.println("-----------------------------------------------------------------\n");
    }
    */
    // -----------------------------------------------------------    

    // --- EDGE IMPULSE C++ SDK INTEGRATION ---
    // Following exactly from: https://docs.edgeimpulse.com/hardware/deployments/run-cpp-overview
    
    size_t feature_count = EI_CLASSIFIER_DSP_INPUT_FRAME_SIZE;
    float *features = (float *)heap_caps_malloc(feature_count * sizeof(float), MALLOC_CAP_SPIRAM);
    if (!features) {
        features = (float *)malloc(feature_count * sizeof(float));
    }
    if (!features) {
        Serial.println("Failed to allocate features buffer!");
        free(rgb888_buf);
        free(scaled_rgb888_buf);
        return false;
    }
    Serial.printf("[stage] features alloc OK ptr=%p\n", features);
    Serial.flush();

    // Populate feature buffer with standard 0xRRGGBB format.
    // ESP32 fmt2rgb888 actually outputs BGR byte order despite the name —
    // the JPEG decoder it wraps produces B at 0, G at 1, R at 2.
    size_t pixel_count = EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT;
    Serial.printf("[stage] feature pack: final_rgb888_buf=%p pixel_count=%u feature_count=%u\n",
                  final_rgb888_buf, (unsigned)pixel_count, (unsigned)feature_count);
    Serial.flush();
    for (size_t i = 0; i < pixel_count && i < feature_count; i++) {
        uint8_t b = final_rgb888_buf[i * 3 + 0];
        uint8_t g = final_rgb888_buf[i * 3 + 1];
        uint8_t r = final_rgb888_buf[i * 3 + 2];
        uint32_t rgb = ((uint32_t)r << 16) | ((uint32_t)g << 8) | b;
        features[i] = static_cast<float>(rgb);
    }
    Serial.println("[stage] feature pack done");
    Serial.flush();

    // Turn the raw buffer into an Edge Impulse signal
    ei::signal_t signal;
    int err_sig = ei::numpy::signal_from_buffer(features, feature_count, &signal);
    if (err_sig != 0) {
        Serial.printf("Failed to create signal from buffer (%d)\n", err_sig);
        free(features);
        free(rgb888_buf);
        if (scaled_rgb888_buf) free(scaled_rgb888_buf);
        return false;
    }

    Serial.println("[stage] signal ready, calling run_classifier");
    Serial.flush();

    ei_impulse_result_t result = { 0 };
    EI_IMPULSE_ERROR err = run_classifier(&signal, &result, false);

    Serial.printf("[stage] run_classifier returned err=%d\n", (int)err);
    Serial.flush();

    // Free all buffers immediately after inference
    free(features);
    free(rgb888_buf);
    if (scaled_rgb888_buf) free(scaled_rgb888_buf);
    Serial.println("[stage] buffers freed");
    Serial.flush();

    if (err != EI_IMPULSE_OK) {
        Serial.printf("Edge Impulse error: %d\n", err);
        return false;
    }

    // Print all predictions for better debugging
    Serial.print("Predictions: ");
    for (size_t i = 0; i < EI_CLASSIFIER_LABEL_COUNT; i++) {
        Serial.printf("%s: %.2f  ", result.classification[i].label, result.classification[i].value);
    }
    Serial.println();

    // Inference timing (milliseconds). 'classification' is the neural-net time
    // that the Tier 1 -O3 / static-arena flags are meant to reduce.
    Serial.printf("Timing: dsp=%d ms, classification=%d ms, anomaly=%d ms\n",
                  result.timing.dsp, result.timing.classification, result.timing.anomaly);

    for (size_t i = 0; i < EI_CLASSIFIER_LABEL_COUNT; i++) {
        if (strcmp(result.classification[i].label, "commercial") == 0) {
            return result.classification[i].value > 0.9f;
        }
    }

    return false;
}

static void sendMuteToggle() {
    Serial.println("Sending IR mute toggle");
    irsend.sendNEC(MUTE_TOGGLE_CODE, 32);
}

static void testEmbeddedImages() {
    Serial.println("\n--- RUNNING EMBEDDED TEST IMAGES ---");
    for (int i = 0; i < 10; i++) {
        Serial.printf("Testing Image %d...\n", i + 1);

        camera_fb_t fake_fb = {0};
        fake_fb.buf = (uint8_t *)test_imgs[i];
        fake_fb.len = test_sizes[i];
        // Test images exported from Edge Impulse are already perfectly sized!
        fake_fb.width = EI_CLASSIFIER_INPUT_WIDTH;
        fake_fb.height = EI_CLASSIFIER_INPUT_HEIGHT;
        fake_fb.format = PIXFORMAT_JPEG;

        classifyCommercial(&fake_fb);
    }
    Serial.println("------------------------------------\n");
}

void setup() {
    Serial.begin(115200);
    delay(1000);

    if (!initCamera()) {
        Serial.println("Camera init failed - halting");
        while (true) {
            delay(1000);
        }
    }

    // Warm up the camera to allow Auto-Exposure and Auto-White-Balance to settle
    Serial.println("Warming up camera...");
    for (int i = 0; i < 10; i++) {
        camera_fb_t *fb = esp_camera_fb_get();
        if (fb) esp_camera_fb_return(fb);
        delay(100);
    }

    irsend.begin();
    pinMode(IR_SEND_PIN, OUTPUT);

    testEmbeddedImages();

    Serial.println("ESP32-CAM Edge Impulse commercial detection started (RGB Model)");
}

void loop() {
    camera_fb_t *fb = esp_camera_fb_get();
    if (!fb) {
        Serial.println("Camera capture failed");
        delay(1000);
        return;
    }

    bool commercialDetected = classifyCommercial(fb);
    esp_camera_fb_return(fb);

    if (commercialDetected) {
        commercialCount++;
        programCount = 0;
    } else {
        programCount++;
        if (commercialCount > 0) {
            commercialCount = 0;
        }
    }

    if (!commercialMode && commercialCount >= COMMERCIAL_CONFIRM_FRAMES) {
        commercialMode = true;
        irsend.sendPronto(muteOnPronto, sizeof(muteOnPronto) / sizeof(muteOnPronto[0]), 2);
        //sendMuteToggle();
        Serial.println("Commercial detected - muting");
    }

    if (commercialMode && programCount >= PROGRAM_CONFIRM_FRAMES) {
        commercialMode = false;
        irsend.sendPronto(muteOffPronto, sizeof(muteOffPronto) / sizeof(muteOffPronto[0]), 2);
        //sendMuteToggle();
        Serial.println("Program resumed - unmuting");
    }

    Serial.printf("commercialCount=%u programCount=%u mode=%s\n",
                  commercialCount, programCount,
                  commercialMode ? "COMMERCIAL" : "PROGRAM");

    //delay(1000);
}
